table Date_table
	lineageTag: 694902aa-3914-47e9-9181-424dbeeec93d

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: b1b4f968-4e4f-4740-80af-5ecd83f58884
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 9745200d-5925-46bb-926f-b27eb75d446a
			defaultHierarchy: LocalDateTable_075a5738-1c24-47bf-9f82-9393fca16410.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Week
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3c2be5a1-68c2-40d2-8531-acf77cf9d6a5
		summarizeBy: none
		sourceColumn: Week

		variation Variation
			isDefault
			relationship: 8b61620a-3765-4db2-9441-195df3ee585e
			defaultHierarchy: LocalDateTable_565cffe7-e118-4baf-8a06-104b21d3b401.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Date - Copy'
		dataType: string
		lineageTag: 3b8c8b23-7eb6-4c85-9fc3-0d98c2565bbf
		summarizeBy: none
		sourceColumn: Date - Copy

		annotation SummarizationSetBy = Automatic

	partition Date_table = m
		mode: import
		source =
				let
				    Source = List.Dates(#date(2024,1,1), 365, #duration(5,0,0,0)),
				    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Sorted Rows" = Table.Sort(#"Converted to Table",{{"Column1", Order.Ascending}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Sorted Rows",{{"Column1", "Date"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Date", type date}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type", "Date", "Date - Copy"),
				    #"Renamed Columns1" = Table.RenameColumns(#"Duplicated Column",{{"Date - Copy", "Week"}}),
				    #"Calculated Start of Week" = Table.TransformColumns(#"Renamed Columns1",{{"Week", Date.StartOfWeek, type date}}),
				    #"Duplicated Column1" = Table.DuplicateColumn(#"Calculated Start of Week", "Date", "Date - Copy"),
				    #"Extracted Month Name" = Table.TransformColumns(#"Duplicated Column1", {{"Date - Copy", each Date.MonthName(_), type text}})
				in
				    #"Extracted Month Name"

	changedProperty = Name

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

