table Orders
	lineageTag: df7b95b9-6ea5-4ff1-8a61-a0cd20267a02

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: f7508861-d7e0-44f5-89cd-27cb4c9e58b6
		summarizeBy: count
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 7db12fe1-f34f-4d3e-b6fa-67466f273faa
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: mmmm yyyy
		lineageTag: 73800830-451b-4184-b678-ffb1876e23f1
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: d0655a66-1488-45f4-a5ec-ee09d230031c
			defaultHierarchy: LocalDateTable_082a0477-b7d5-4bb2-b0f4-43b3b43ecdd1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Ship Date'
		dataType: dateTime
		formatString: mmmm d
		lineageTag: 3235aabf-93b7-4223-b26f-0a92af2dbcbe
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: 67bee893-f122-402f-9313-86dcdb88701e
			defaultHierarchy: LocalDateTable_dc76c65a-575f-4fb7-a3e3-bc71eb8e1650.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Ship Mode'
		dataType: string
		lineageTag: 86287038-ae91-4c5f-bd33-820aa9cbde1d
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: e4ca0824-1d1e-4b20-a312-b2a242067176
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 61b4ade2-3ce4-473a-8ce2-0661c2424331
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 3b662176-d4f8-41a4-bcdf-96815ae0c431
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: b7ef2e92-abdd-45f4-b07e-e43a3b916f8e
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 3ced4207-6023-48fd-b631-7a55c3d78263
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 528c93f5-4b5d-4abe-bac4-f0e8e5eeb127
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: ce1792e5-e373-4bb4-b4e4-b6aa82c00719
		summarizeBy: count
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: a14a9916-d16e-4303-a107-83962bad2c16
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: fb6b037e-d7d8-450b-bd8c-a41b85329ab3
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 6da2a402-442e-47ee-84da-19aed21df40a
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: c6878aeb-595e-46cf-9b3b-c12eb631c555
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 09f744b5-18f0-44ed-a252-2ef69f12f21a
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: 9ba8aa77-bb95-4124-9d94-7cb36af25651
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 536ac29b-87c0-476d-afae-efc7350bce52
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		lineageTag: b32fa935-f3e2-4f04-9c28-196f26f86a86
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: 6fdd8df4-3963-4c40-8f5a-567ba3b94e8b
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Orders = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Hp\Desktop\youtube contents\POWER BI Class 1\Dataset\Sample - Superstore.xls"), null, true),
				    Orders1 = Source{[Name="Orders"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Orders1, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Row ID", Int64.Type}, {"Order ID", type text}, {"Order Date", type date}, {"Ship Date", type date}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Customer Name", type text}, {"Segment", type text}, {"Country", type text}, {"City", type text}, {"State", type text}, {"Postal Code", Int64.Type}, {"Region", type text}, {"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

